export const LoginActionTypes = {
  LOGIN_SUBMIT: 'LOGIN_SUBMIT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER_SUBMIT: 'REGISTER_SUBMIT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR'
};

export const RenderActionTypes = {
  RENDER_MAIN_PAGE: 'MAIN_PAGE',
  RENDER_NAVBAR: 'RENDER_NAVBAR',
  RENDER_FOOTER: 'RENDER_FOOTER',

  RENDER_AUTH_REG_PAGE: 'RENDER_AUTH_REG_PAGE',
  RENDER_MOVIE_PAGE: 'RENDER_MOVIE_PAGE',
  RENDER_STATS_PAGE: 'RENDER_STATS_PAGE',
  RENDER_PERSON_PAGE: 'RENDER_PERSON_PAGE',
  RENDER_PROFILE_PAGE: 'RENDER_PROFILE_PAGE',

  RENDER_CSAT_PAGE: 'RENDER_CSAT_PAGE',
  RENDER_CSAT: 'RENDER_CSAT'
};

export const GetDataActionTypes = {
  PERSON_NOT_FOUND_ERROR: 'PERSON_NOT_FOUND_ERROR',
  SESSION_NOT_FOUND_ERROR: 'SESSION_NOT_FOUND_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};

export const MainActionTypes = {
  LOAD_MAIN_DATA: 'LOAD_MAIN_DATA',
  MAIN_DATA_LOADED: 'MAIN_DATA_LOADED',
  MAIN_DATA_ERROR: 'MAIN_DATA_ERROR'
};

export const MovieActionTypes = {
  LOAD_MOVIE_DATA: 'LOAD_MOVIE_DATA',
  MOVIE_DATA_LOADED: 'MOVIE_DATA_LOADED',
  MOVIE_DATA_ERROR: 'MOVIE_DATA_ERROR',
  LOAD_MOVIE_REVIEWS_DATA: 'LOAD_MOVIE_REVIEWS_DATA',
  MOVIE_REVIEWS_DATA_LOADED: 'MOVIE_REVIEWS_DATA_LOADED',
  POST_MOVIE_REVIEW: 'POST_MOVIE_REVIEW'
};

export const UserPageTypes = {
  UPDATE_USER_PAGE: 'UPDATE_USER_PAGE',
  GET_USER: 'GET_USER',
  UPDATE_USER: 'UPDATE_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  NO_SESSION: 'NO_SESSION',
  UPDATE_USER_AVATAR: 'UPDATE_USER_AVATAR'
};

export const StatsActionTypes = {
  LOAD_STATS_DATA: 'LOAD_STATS_DATA',
  STATS_DATA_LOADED: 'MOVIE_STATS_LOADED',
  STATS_DATA_ERROR: 'MOVIE_STATS_ERROR'
};
