export const LoginActionTypes = {
  LOGIN_SUBMIT: 'LOGIN_SUBMIT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  REGISTER_SUBMIT: 'REGISTER_SUBMIT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR'
};
